
name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  publish-canary:
    name: Publish Canary Version
    runs-on: ubuntu-latest
    if: contains(github.actor, 'renovate') == false
    steps:
      - name: Checkout Master
        uses: actions/checkout@v1
      - name: Use Node
        uses: actions/setup-node@master
        with:
          node-version: '13.x'
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install Dependencies using Yarn
        run: yarn install
      - name: Build
        run: yarn build
      - name: Release Canary
        id: canary
        uses: 'kamilkisiela/release-canary@master'
        if: github.repository == 'ardatan/graphql-toolkit'
        with:
          npm-token: ${{ secrets.NODE_AUTH_TOKEN }}
          npm-script: 'ci:release:canary'
      - name: Publish a message
        if: steps.canary.outputs.released
        uses: 'kamilkisiela/pr-comment@master'
        with:
          message: |
            The latest changes of this PR are available as alpha in npm: `${{ steps.canary.outputs.version }}`
            
            Quickly update your package.json by running:
            
                npx match-version @graphql-toolkit ${{ steps.canary.outputs.version }}
          bot-token: ${{ secrets.GH_API_TOKEN }}
          bot: 'theguild-bot'
          github-token: ${{ secrets.GITHUB_TOKEN }}
  test:
    name: Testing on ${{matrix.os}} and Node ${{matrix.node_version}} w/ GraphQL ${{matrix.graphql_version}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        node_version: [10, 12, 13]
        graphql_version: [latest, legacy]
    steps:
      - name: Checkout Master
        uses: actions/checkout@v1
      - name: Use Node ${{matrix.node_version}}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node_version }}
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install Legacy GraphQL
        run: yarn add -D -W graphql@14 && node ./scripts/match-graphql.js
        if: matrix.graphql_version == 'legacy'
      - name: Install Dependencies using Yarn
        run: yarn install
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
